version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventarios-app-image
    container_name: inventarios-app-container
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_SSLMODE=require
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge