version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventarios-app-image
    container_name: inventarios-app-container
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSLMODE=require
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge